name: baby_gallery
description: A baby gallery app for CeylonEdge internship assessment.

# Flutter version: 3.x.x (replace with your version)
# Dart version: 3.x.x (replace with your version) 
# Java version: xx.x.x (replace with your version)

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true